### ISSUE TITLE
Does not have .env instruction in Installation.md.

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [0CreepySmile0/ku-polls#28]
Installation.md does not tell anything about environment variable configuration.

**Comment by 0CreepySmile0** [comment]
Now, has instruction for environment variables configuration. see [updated](https://github.com/0CreepySmile0/ku-polls/blob/34ec67c6a7c47b47e3c8a8ec7484d8828630c981/Installation.md#set-environment-variables)
